apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-r
data:
  schema-r.json: |
    {
      "type": "object",
      "properties": {
          "firstName": {
              "type": "string"
          },
          "lastName": {
              "type": "string"
          },
          "age": {
              "type": "integer"
          }
      },
      "required": ["firstName", "lastName"]
    }
  
---
apiVersion: jobico.coeux.dev/v1
kind: Job
metadata:
  name: job-for-rust
spec:
  events:
    - name: greet
      wasm: greet.wasm
      schema:
        key: schema-r
